# Generated by Django 5.0.6 on 2024-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, unique=True)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
